language: python
matrix:
  include:

    # Linux
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
      env: PYINSTALLER_BUILD=true
    - os: linux
      python: 3.7

    # OSX
    - os: osx
      osx_image: xcode11
      language: shell
      env: PYINSTALLER_BUILD=true
      before_install:
        - pyenv install 3.6.9
        - pyenv local 3.6.9
    - os: osx
      osx_image: xcode11
      language: shell

    # Windows
    # - os: windows
    #   language: shell
    #   before_install:
    #     - choco install python --version=3.6.8
    #     - choco install visualstudio2017-workload-python
    #     - choco install make
    #     - python -m pip install -U pip
    #   env:
    #     - PATH=/c/Python36:/c/Python36/Scripts:$PATH
    #     - PYINSTALLER_BUILD=true

install: make deps
script:
  - make test
  - make pyinstaller
# deploy:
#   provider: releases
#   api_key: $GITHUB_TOKEN
#   file: ./dist/minet
#   skip_cleanup: true
#   on:
#     branch: master
#     tags: true
#     condition: $PYINSTALLER_BUILD = true
