language: python
matrix:
  include:

    # Linux
    - os: linux
      python: 3.4
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
      env: PYINSTALLER_BUILD=true
    - os: linux
      python: 3.7

    # OSX
    - os: osx
      osx_image: xcode11
      language: shell
      env: PYINSTALLER_BUILD=true
      before_install:
        - pyenv versions

    # Windows
    # - os: windows
    #   language: shell
    #   before_install:
    #     - choco install python --version=3.6.8
    #     - choco install visualstudio2017-workload-python
    #     - choco install make
    #     - python -m pip install -U pip
    #   env:
    #     - PATH=/c/Python36:/c/Python36/Scripts:$PATH
    #     - PYINSTALLER_BUILD=true

install: make deps
script:
  - make test
  - make pyinstaller
