language: python
matrix:
  include:

    # Linux
    - os: linux
      python: 3.5
      dist: xenial
    - os: linux
      python: 3.6
      env: PYINSTALLER_BUILD=true PYINSTALLER_BUILD_NAME=minet_linux_xenial
      dist: xenial
    - os: linux
      python: 3.7
      dist: xenial

    # Older linux
    - os: linux
      python: 3.6
      env: PYINSTALLER_BUILD=true PYINSTALLER_BUILD_NAME=minet_linux_trusty
      dist: trusty
    - os: linux
      python: 3.6
      env: PYINSTALLER_BUILD=true PYINSTALLER_BUILD_NAME=minet_linux_precise
      dist: precise
      before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get update -y
        - sudo apt-get install -y g++-4.8
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50

    # OSX
    - os: osx
      osx_image: xcode11
      language: shell
      env: PYINSTALLER_BUILD=true PYINSTALLER_BUILD_NAME=minet_osx
      before_install:
        - pyenv install 3.6.9
        - pyenv local 3.6.9
    - os: osx
      osx_image: xcode11
      language: shell

    # Windows
    # - os: windows
    #   language: shell
    #   before_install:
    #     - choco install python --version=3.6.8
    #     - choco install visualstudio2017-workload-python
    #     - choco install make
    #     - python -m pip install -U pip
    #   env:
    #     - PATH=/c/Python36:/c/Python36/Scripts:$PATH
    #     - PYINSTALLER_BUILD=true

install: make deps
script:
  - make test
  - make pyinstaller
  - if [[ $PYINSTALLER_BUILD = true ]]; then mv ./dist/minet ./dist/$PYINSTALLER_BUILD_NAME; fi
  - ls -lh ./dist
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: ./dist/$PYINSTALLER_BUILD_NAME
  skip_cleanup: true
  on:
    branch: master
    tags: true
    condition: $PYINSTALLER_BUILD = true
