language: python
matrix:
  include:
    - os: linux
      python: 3.4
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
      env: PYINSTALLER_BUILD=true
    - os: linux
      python: 3.7
    - os: osx
      python: 3.6
    - os: osx
      python: 3.7
    - os: windows
      python: 3.6
    - os: windows
      python: 3.7
install: make deps
script: make test
