language: python
matrix:
  include:
    - os: linux
      python: 3.4
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
      env: PYINSTALLER_BUILD=true
    - os: linux
      python: 3.7
    - os: osx
      osx_image: xcode11
      language: shell
      env: PYINSTALLER_BUILD=true
      before_install:
        - pyenv versions
    - os: windows
      language: shell
      before_install:
        - choco install python --version=3.6.8
        - python -m pip install -U pip
      env:
        - PATH=/c/Python36:/c/Python36/Scripts:$PATH
        - PYINSTALLER_BUILD=true
install: make deps
script: make test
